### ISSUE TITLE
RBAC issues with secrets and configmaps

### ISSUE THREAD

**Issue by ykoer** [yard-turkey/awss3operator#1]
My aws-s3-provisioner runs in the **openshift-operators** namespace. If I create an obc object in another namespace, I see following error in the aws-s3-provisioner logs:

`E0114 19:49:05.531559       1 resourcehandlers.go:125]  "msg"="probably not fatal, retrying" "error"="secrets is forbidden: User \"system:serviceaccount:openshift-operators:aws-s3-provisioner-1-0-0\" cannot create resource \"secrets\" in API group \"\" in the namespace \"testing\"" "key"="testing/bucket-test04"`

Could you please add secrets and configmaps resources to the clusterPermissions as well?

```
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - 'create'
```

Thanks
Yusuf
